name: Mozilla Israel
markdown: kramdown

pygments: false

repo-url: https://github.com/MozillaIsrael/MozillaIsrael-www/blob/gh-pages
url: https://MozillaIsrael.github.io/MozillaIsrael-www
baseurl: /MozillaIsrael-www/

direction: rtl
language: he
